# Grid console http://localhost:4444/ui/index.html#/
# Remote driver http://localhost:4444/

version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.0.0
    ports:
      - "4442-4444:4442-4444"

  chrome:
    image: selenium/node-chrome:88.0
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm # avoid Chrome crash for lack of space
      - ./evidences:/home/evidences
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    deploy:
      replicas: 1
    ports:
      - "5901:5900"

  firefox:
    image: selenium/node-firefox:85.0
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
      - ./evidences:/home/evidences
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    deploy:
      replicas: 1
    ports:
      - "5902:5900"

  edge:
    image: selenium/node-edge:4.0.0
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
      - ./evidences:/home/evidences
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    deploy:
      replicas: 1
    ports:
      - "5903:5900"

  opera:
    image: selenium/node-opera:74.0
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
      - ./evidences:/home/evidences
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    deploy:
      replicas: 1
    ports:
      - "5904:5900"